services:
  back:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    image: ghcr.io/hallboard-team/back-dotnet9-dev:latest
    container_name: back_dev
    volumes:
      - .:/workspaces/back
      - vscode-server-cache:/root/.vscode-server
      - vscode-user-extensions:/root/.vscode-server/extensions
    ports:
      - "5000:5000"

volumes:
  vscode-server-cache:
  vscode-user-extensions:
