services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
      args:
        DOTNET_VERSION: ${DOTNET_VERSION:-9.0}
    image: ghcr.io/hallboard-team/api-dotnet${DOTNET_VERSION:-9.0}-dev:latest
    container_name: ${CONTAINER_NAME:-api_dev}
    user: "1000:1000"
    volumes:
      - ./:/workspaces/app:Z
      - ~/.cache/vscode-server-shared:/home/vscode/.vscode-server-shared:Z
    environment:
      - VSCODE_SERVER_DIR=/home/vscode/.vscode-server-shared
    command: ["sleep", "infinity"]
    ports:
      - "${PORT:-5000}:5000"
