version: "3.9"

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DOTNET_VERSION: ${DOTNET_VERSION:-9.0}
    image: ghcr.io/hallboard-team/back-dotnet${DOTNET_VERSION:-9.0}-dev:latest
    container_name: ${CONTAINER_NAME:-back_dev}
    volumes:
      - .:/workspaces/back
      # Shared VS Code cache across all containers / users
      - ~/.cache/vscode-server:/root/.vscode-server
    ports:
      - "${PORT:-5000}:5000"
