version: "3.9"

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/hallboard-team/back-dotnet9-dev:latest
    container_name: ${CONTAINER_NAME:-back_dev}
    volumes:
      - .:/workspaces/back
      - vscode-server-cache:/root/.vscode-server
      - vscode-user-extensions:/root/.vscode-server/extensions
    ports:
      - "${PORT:-5000}:5000"

volumes:
  vscode-server-cache:
  vscode-user-extensions:
